server:
  port: 8082

spring:
  application:
    name: auth-service

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://127.0.0.1:27017/flow_ops}

logging:
  level:
    root: info
    org.springframework.security: debug

opsflow:
  JWT_SECRET: ${JWT_SECRET:YOURVALIDKEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, info, metrics, mappings, prometheus, threaddump
  metrics:
    tags:
      application: auth-service
