server:
  port: 8082

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME:fairfree.app@gmail.com}
    password: ${MAIL_PASSWORD:bwlynuqomhlkesep}
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtps.ssl.trust: smtp.gmail.com

  application:
    name: FlowOps
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.miu.flowops
        spring.json.value.default.type: com.miu.flowops
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

      acks: all
      retries: 3

  data:
    mongodb:
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
          - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  mongodb:
    uri: mongodb://127.0.0.1:27017/flow_ops


logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, info, metrics, mappings, prometheus, threaddump
