global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8080"]
    scrape_interval: 10s

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:8085"]
    scrape_interval: 10s

  - job_name: "release-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["release-service:8081"]
    scrape_interval: 10s

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:8082"]
    scrape_interval: 10s

  - job_name: "chat-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["chat-service:8083"]
    scrape_interval: 10s

  - job_name: "forum-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["forum-service:8084"]
    scrape_interval: 10s
