#Scrap metrics from /actuator/prometheus on regular interval from specified port.
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:8082"]
        labels:
          service: "auth-service"

  - job_name: "release-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["release-service:8081"]
        labels:
          service: "release-service"

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:8083"]
        labels:
          service: "notification-service"

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8085"]
        labels:
          service: "api-gateway"

  - job_name: "chatbot-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["chatbot-service:8084"]
        labels:
          service: "chatbot-service"
